### ISSUE TITLE
Preserve colorized output?

### ISSUE THREAD

**Issue by danawoodman** [strongloop/node-foreman#72] opened 2015-05-04 00:04 UTC
Would it be possible for foreman to preserve colorized output? E.g. output from `console.log` using something like [chalk](https://github.com/sindresorhus/chalk)?

**Comment by Darkhogg** [comment] 2015-05-11 14:57
It already does. The problem is probably due to stdin not being a terminal. Try forcing color output in chalk.

**Comment by dickeyxxx** [comment] 2016-03-29 05:20
@rmg I think we can close this

**Closed** 2016-04-12 19:06 UTC

**Comment by hai-cea** [comment] 2016-09-24 15:19
This fixed it for me:
```
chalk.enabled = true;
```

**Comment by pioneerskies** [comment] 2016-12-15 08:21
Here there is not a reference about how to troubleshoot nor resolve the issue. Trying with webpack output and I can't afford to keep it colorized. Should I open another issue for this?

**Comment by michaek** [comment] 2017-04-27 21:16
Another way to achieve this would be to set the FORCE_COLOR environment variable, as described in the chalk documentation: https://github.com/chalk/chalk#chalksupportscolor Useful when a library you're consuming uses chalk.
